// Generated by CoffeeScript 1.9.2
(function() {
  var maxProfit;

  maxProfit = function(prices) {
    var i, idx, len, price, profit;
    profit = 0;
    for (idx = i = 0, len = prices.length; i < len; idx = ++i) {
      price = prices[idx];
      if (idx > 0 && price > prices[idx - 1]) {
        profit += price - prices[idx - 1];
      }
    }
    return profit;
  };

  console.log(maxProfit([4, 5, 6]));

}).call(this);
