// Generated by CoffeeScript 1.9.2
(function() {
  var TreeNode, maxDepth;

  TreeNode = require("./TreeNode");

  maxDepth = function(root) {
    var max;
    max = function(x, y) {
      if (x > y) {
        return x;
      } else {
        return y;
      }
    };
    if (root) {
      return max(maxDepth(root.left, maxDepth(root.right))) + 1;
    } else {
      return 0;
    }
  };

}).call(this);

//# sourceMappingURL=MaximumDepthOfBinaryTree.js.map
