// Generated by CoffeeScript 1.9.2
(function() {
  var TreeNode, isSameTree, p, q;

  TreeNode = require('./TreeNode');

  isSameTree = function(p, q) {
    if (!p && !q) {
      return true;
    } else if (!p || !q || p.val !== q.val) {
      return false;
    } else {
      return isSameTree(p.left, q.left) && isSameTree(p.right, q.right);
    }
  };

  p = new TreeNode(1);

  q = new TreeNode(1);

  console.log(isSameTree(p, q));

}).call(this);

//# sourceMappingURL=SameTree.js.map
