// Generated by CoffeeScript 1.9.2
(function() {
  var singleNumber;

  singleNumber = function(nums) {
    return nums.reduce(function(t, s) {
      return t ^ s;
    });
  };

  console.log(singleNumber([1, 1, 2, 3, 3, 4, 4]));

}).call(this);

//# sourceMappingURL=SingleNumber.js.map
