// Generated by CoffeeScript 1.9.2
(function() {
  var TreeNode;

  TreeNode = (function() {
    function TreeNode(val) {
      this.val = val;
      this.left = this.right = null;
    }

    return TreeNode;

  })();

  module.exports = TreeNode;

}).call(this);

//# sourceMappingURL=TreeNode.js.map
